
name: Generate Code Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install

      - name: Generate image
        run: node scripts/generate_image.js

      - name: Commit image
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add preview.png
          git commit -m "auto: add preview image" || echo "no changes"
          git push
